version: '3'

services:
  metabase_app:
    image: metabase/metabase
    container_name: metabase_app
    volumes:
      - ~/local-metabase-data:/metabase-data
    ports:
      - "3000:3000"
#    environment:
#      MB_DB_FILE: /metabase-data/metabase.db
#      MB_DB_CONNECTION_URI: "${MB_DB_CONNECTION_URI}"
    env_file:
      - local.env # to get `MB_DB_CONNECTION_URI` variable
    networks:
      metabase_app_nw:

#  metabase_database:
#    image: postgres:9.6
#    ports:
#      - "5440:5432"
#    environment:
#      - "POSTGRES_USER=metabase_user"
#      - "POSTGRES_DB=metabase"
#      - "POSTGRES_PASSWORD=metabase_password"
#    volumes:
#      - ~/postgresql_metabase_db/:/var/lib/postgresql
#    container_name: metabase_database
#    networks:
#      metabase_app_nw:

networks:
  metabase_app_nw:
